### ISSUE TITLE
importLocal(__filename) returning an empty object, leading to local install which does not exist and skipping all ava tests

### ISSUE THREAD

**Issue by revelt** [sindresorhus/import-local#6] opened 2019-07-15 14:29 UTC
hi Sindre, maintainers and everybody else,

I would like to report a very strange issue and I hope you'll be able to shine some light on it.

I found that my `ava`, installed as a devdependency, was doing nothing, just silently exiting without an error. I placed some `console.log`s in the files in `node_modules` and it lead to this package, `import-local` — specifically, `require(localFile)` was returning an empty plain object:

```js
return !filenameInLocalNodeModules && localFile && require(localFile);
```

now `true` + `true` + `{}` =  empty plain object `{}` and it's truthy, which caused line `if (importLocal(__filename))` to just do nothing:

```js
if (importLocal(__filename)) {
	console.log('Using local version of this package');
} else {
	// Code for both global and local version here…
}
```

There was no globally installed package (ava) but `importLocal` above was returning truthy empty object and there was nowhere to run the tests on.

**Do you have a clue what is going on?**

By the way, if I clone this repo, `npm i` and run tests, they fail the "global" test:

<img width="270" alt="test" src="https://user-images.githubusercontent.com/8344688/61222673-0fa1f400-a713-11e9-9849-77c16fd78f79.png">

What's also strange, my GItLab CI also has this issue and this morning ava unit tests seem to have silently skipped on the CI. That's Linux on a clean slate so something really strange is going on.

**Maybe we should add more checks, for example, does `importLocal(__filename)` result object have keys (if it's an object)?**

Thank you.

**Comment by gjbkz** [comment] 2019-07-16 01:41
Hi @revelt, I have the same issue and I wrote #5 that will fix it. Using ava@2.1.0 is my workaround.

**Comment by revelt** [comment] 2019-07-16 03:24
@kei-ito I'm on lerna too! So it might be a Lerna thing... I'll keep the issue open until #5 lands and then close this. Thank you very much!

**Comment by shellscape** [comment] 2019-07-21 16:26
I'm getting the same thing using yarn workspaces. User reported that my CLI had stopped working when in a subdirectory of a repo.

Reproduction Repo: https://github.com/aaronjensen/webpack-nano-0.6.3-subdirectory-repro
Reported Issue: https://github.com/shellscape/webpack-nano/issues/13

I've confirmed that the cause is the same. Returned object from require is `{}`.

**Comment by NetOpWibby** [comment] 2019-07-24 02:37
Got the same issue and tracked it back to this. I had to settle for using ava `2.0.0` and getting [`updates`](https://www.npmjs.com/package/updates) to ignore ava via `updates --update ./ --exclude ava`.

**Comment by sindresorhus** [comment] 2019-07-24 06:32
Fixed by https://github.com/sindresorhus/import-local/pull/5

**Closed as completed by sindresorhus** 2019-07-24 06:32 UTC
