### ISSUE TITLE
import-local not work for windows when gloab module and local module in different drive

### ISSUE THREAD

**Issue by slgluo** [sindresorhus/import-local#10] opened 2021-08-28 15:54 UTC
As mentioned in the title, in this line:
`const filenameInLocalNodeModules = !path.relative(localNodeModules, filename).startsWith('..');`
`filenameInLocalNodeModules ` always `true`，because `path.relative(localNodeModules, filename)` always return `filename`. However, it is a absolute path and it does not start with “..”

**Comment by sindresorhus** [comment] 2021-08-29 17:21
Duplicate of https://github.com/sindresorhus/import-local/pull/9

**Closed as completed by sindresorhus** 2021-08-29 17:21 UTC
